---
- hosts: all
  become: yes
  tasks:
  - name: i want to install nginx
    apt:
     name: nginx
     state: present
  - name: i want install git
    apt:
     name: git
     state: present
  - name: iwant to install java
    apt:
     name: openjdk-11-jdk
     state: present